### ISSUE TITLE
cytanb.TableToSerializable が、非負の数値でもArrayNumberTagを付加している

### ISSUE THREAD

**Issue by oocytanb** [oocytanb/cytanb-vci-lua#4]
例えば、`{100, 200, 300, 400}` のような配列では、負の数値が含まれていないので、手を加えずにそのままにしておきたい。
現状のコードは、数値インデックスであれば常に `ArrayNumberTag` を付加している。

**Comment by KatoIppei** [comment]
負数があると上手く動作しないのではなく、多重の連想配列ではない配列であればjsonのserializeとparseで元に戻せなくなります。
多重の連想配列ではない配列の時だけに付けたいのは確かなのでそれを事前に判別できるとよいのですが。

**Comment by oocytanb** [comment]
負の数値であるかは関係なく、MoonSharp の json.serialize/parse に、数値インデックスの多次元配列を渡すと、問題が発生するのですね。なるほどです。

**Comment by KatoIppei** [comment]
例えばですが、
				if type(k) == 'number' then
					k = cytanb.ArrayNumberTag .. k
				end
この部分を、
				if type(k) == 'number' and type(v) == 'table' then
					k = cytanb.ArrayNumberTag .. k
				end
にするとかでしょうか？
負数への対応に漏れが発生しないか確認が必要ですが、これでTagの付く量は減らせるかと。

**Comment by oocytanb** [comment]
負の数値に絡んで発生するバグだと、私が思い違いしていたものですので、このままでいきましょう。

実際に何が起こるのかを試して理解しました。
`json.parse('[[100, 200]]')` こういうコードで、`Unexpected token : '100, 200'` が発生するのですね。
json.parse は手の焼ける子ですねぇ。

この issue は閉じておきます。
