### ISSUE TITLE
GetSubItemTransformのcytanb_transform_tからposition,rotation,scale等を返す関数が欲しい。

### ISSUE THREAD

**Issue by KatoIppei** [oocytanb/cytanb-vci-lua#9]
最近、Messageでtransformのデータを送る際にGetSubItemTransform関数を使用したのですが、数値をVector3にそれぞれ変換するプログラムが長くなってしまう。
>                local pos = Vector3.__new(message.Player[i].Pawn[j].positionX,message.Player[i].Pawn[j].positionY,
>                                          message.Player[i].Pawn[j].positionZ)
>                local rot = Quaternion.__new(message.Player[i].Pawn[j].rotationX,message.Player[i].Pawn[j].rotationY,
>                                             message.Player[i].Pawn[j].rotationZ,message.Player[i].Pawn[j].rotationW)
>                GeisterCore.PlayerArray[i].Pawn[j].SubItem.SetPosition(pos)
>                GeisterCore.PlayerArray[i].Pawn[j].SubItem.SetRotation(rot)

なので、GetSubItemTransformをposition,rotation,scaleに戻す関数がほしいです。
形状としては
>関数名 = function(cytanb_transorm_t)
>    return {
>        position = Vector3.__new(cytanb_transorm_t.positionX,cytanb_transorm_t.positionY,cytanb_transorm_t.positionZ),
>        rotation = Quaternion.__new(cytanb_transorm_t.rotationX,cytanb_transorm_t.rotationY,cytanb_transorm_t.rotationZ,cytanb_transorm_t.rotationW)
>        scale = Vector3.__new(cytanb_transorm_t.scaleX,cytanb_transorm_t.scaleY,cytanb_transorm_t.scaleZ)
>    }
>end,

このようなものが良いと考えています。
関数名とこのposition,rotation,scaleの情報が含まれるアノテーション用クラス名等はoOさんの思い等があると思うのでIssueとして挙げました。

**Comment by oocytanb** [comment]
ご意見ありがとうございます。
確かに、あったほうがお手軽でよいかもしれませんね。
ただ、適当な関数名が思い浮かびません。どうしましょうかね。`InstantiateTransform` とか？
(`GetSubItemTransform` の時点で、いまひとつという話もあります :P)

それから、戻り値に関しては、テーブルを返すかわりに、 戻り値のリストを返す実装がよさそうに思うのですが、いかがでしょう？
テーブルのキー名までユーザーがアクセスするひと手間を省くことができて、分かりやすいと考えています。

```
InstantiateTransform = function (cytanb_transform_t) return Vector3.__new(省略), Quaternion.__new(省略), Vector3.__new(省略) end

-- 使う側
local pos, rot, scale = InstantiateTransform(foo)
```

**Comment by KatoIppei** [comment]
関数の内容についてはoOさんの記載内容で問題ないです。
関数名の方がよほど問題・・・。
RestoreCytanbTransformはいかがでしょうか。

**Comment by oocytanb** [comment]
ですよね。名前を考えていただき、ありがとうございます。
もともとの `GetSubItemTransform` 自体がよい関数ではないのですよね。
`Vector3 <=> table {x, y, z}`, `Quaternion <=> table {x, y, z, w}` の変換関数くらいがよかったかなと。

**Comment by oocytanb** [comment]
提案いただいた `RestoreCytanbTransform` として、関数を追加してみました。

**Comment by KatoIppei** [comment]
ありがとうございます。
table変換という点で考えると、あると便利？なものとしては、
https://virtualcast.jp/wiki/doku.php?id=vci:script:reference:cstypes
上記URLに記載のある
- Vector2
- Vector3
- Vector4
- Color
- Quaternion
- Matrix4x4
になるのかなと思います。（TimeSpanはFromTicksがあるため除外）
このTable変換がTableFromSerializable内で自動的に実施されて、
Vector3をそのままEmitMessageで送って渡せると良いのかな？と思うもののちょっと肥大化しすぎてて難しいなと感じてもいます。
ExportTransformがタイプだったら、GetNameしてその名前をEmitMessageで送って、
受け取ったほうでGetSubItem()するというのもありなのかな？と考えたり。
ただ、ExportTransformはこれができてもExportEffekseerはこれができなかったり(参照し直せるだけの情報が自身に無い)するので全部に対応できず中途半端になってしまう。
書くだけ書きましたが、私の頭でも全然まとまらないので上記は妄想扱いにしてください。
改めて、対応ありがとうございます。
この件はクローズします。

**Comment by oocytanb** [comment]
私も、`TableFromSerializable` で自動変換できたら、ベストだと考えています。
`ExportTransform` と `ExportEffekseer` を扱うのは難しいので除いたとして、列挙していただいた 6タイプがよいでしょうね。
From のほうは、おそらく実装できるでしょう。

`TableToSerializable` も自動で Vector などを table に変換してあげたいところですが、`userdata` 型を判別するよさそうな方法が分かりません。
なければ、手動で `Vector3ToTable` のような関数を通せば良いかな。
table の内容は、型情報+成分 `{['#__CYTANB_TABLE'] = 'Vector3', x, y, z}` を戻せばきっとうまくと思うのです。

このあたりまで実装出来たら、`GetSubItemTransform` は非推奨関数にしたい気持ちです。

**Comment by oocytanb** [comment]
`Vector3` と `Quaternion` の `ToTable/FromTable` を実装しました。問題がなければ他の型についても進めようと思います。
さらに、`TableFromSerializable` に自動変換の処理を実装しました。`Vector3ToTable` 等で変換したテーブルが含まれている場合は、`Vector3` 等に戻すようになっています。

**Comment by oocytanb** [comment]
`Color`, `Vector2`, `Vector4` の `ToTable/FromTable` を実装しました。`Matrix4x4` についてはいずれ。
